- name: Synchronize war file and Restart Service
  hosts: all
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: "{{ lookup('env', 'pem_key_path') }}"
  tasks:
    - name: Synchronize war file to the target
      synchronize:
        src: /var/lib/jenkins/workspace/nunu/build/libs/nunu.war
        dest: /usr/local/tomcat9/webapps/nunu.war
        mode: push
 
    - name: Shutdown the service
      command: /usr/local/tomcat9/bin/shutdown.sh
      become: yes   # 관리자 권한이 필요한 경우 사용


    - name: Wait for a few seconds
      pause:
        seconds: 2   # 필요에 따라 대기 시간을 조정
        
    - name: Start the service
      command: bin/startup.sh
      become: yes   # 관리자 권한이 필요한 경우 사용
      args:
        chdir: /usr/local/tomcat9/   # 해당 디렉토리로 이동하여 명령을 실행하려면 사용