- name: Synchronize war file and Restart Service
  hosts: all
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: "{{ lookup('env', 'pem_key_path') }}"
  tasks:
    - name: Synchronize war file to the target
      become: yes
      synchronize:
        src: /var/lib/jenkins/workspace/nunu/build/libs/nunu.war
        dest: /usr/local/tomcat9/webapps/nunu.war
        mode: push
 
    - name: Shutdown the service
      command: /usr/local/tomcat9/bin/shutdown.sh
      args:
        chdir: /usr/local/tomcat9/
      become: yes   # 관리자 권한이 필요한 경우 사용
     
    - name: Start the service
      command: /usr/local/tomcat9/bin/startup.sh
      become: yes